version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.0-node-browsers
      - image: circleci/mariadb:10.4
    # environment:
    #   - DB_CONNECTION: circle_testing
    # working_directory: ~/circleci
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      # - run:
      #     name: Docker php extensions install
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - save_cache:
          key: v1-composer-{{ checksum "package-lock.json" }}
          paths:
            - vendor
      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run:
          name: Run PHPUnit
          command: vendor/bin/phpunit