version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.0-node-browsers
      - image: circleci/mariadb:10.4
    # environment:
    #   - DB_CONNECTION: circle_testing
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Docker php extensions install
          command: sudo docker-php-ext-install pdo_mysql
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/laravelapp/composer.json" }}
            - v1-dependencies-
      - run: rm -rf src/laravelapp/vendor/composer/installed.json 
      - run: rm src/laravelapp/composer.lock
      - run: composer global clearcache
      - run: 
          working_directory: src/laravelapp
          name: Install PHP libraries
          command: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "src/laravelapp/composer.json" }}
      - run:
          name: Run PHPUnit
          command: src/laravelapp/vendor/bin/phpunit